/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author DLHa
 */
public class QuanLy extends javax.swing.JFrame {

    private String maTK;
    private String loaiTK;

    /**
     * Creates new form QuanLy
     */
    public QuanLy(String maTK, String loaiTK) {
        initComponents();
        this.maTK = maTK;
        this.loaiTK = loaiTK;
        if (loaiTK.equals("nhan vien ban hang")) {
            jbQuanLySach.setEnabled(false);
            jbQuanLyPN.setEnabled(false);
            jbQuanLyNCC.setEnabled(false);
        }
        if (loaiTK.equals("nhan vien kho")) {
            jbQuanLyNCC.setEnabled(false);
        }
        this.setLocationRelativeTo(this);
    }

    public QuanLy() {
        initComponents();  ////dùng khởi tạo các thành phần giao diện người dùng và các sự kiện
        this.setLocationRelativeTo(this); // đặt cửa sổ hiển thị ở trung tâm màn hình
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbQuanLyNV = new javax.swing.JButton();
        jbQuanLyKH = new javax.swing.JButton();
        jbQuanLyTK = new javax.swing.JButton();
        jbQuanLySach = new javax.swing.JButton();
        jbQuanLyPN = new javax.swing.JButton();
        jbQuanLyNCC = new javax.swing.JButton();
        jbTroLai = new javax.swing.JButton();
        jbQuanLyPN1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(241, 202, 164));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("QUẢN LÝ ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(243, 231, 231));

        jbQuanLyNV.setBackground(new java.awt.Color(0, 0, 0));
        jbQuanLyNV.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbQuanLyNV.setForeground(new java.awt.Color(255, 255, 255));
        jbQuanLyNV.setText("QUẢN LÝ NHÂN VIÊN");
        jbQuanLyNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbQuanLyNVActionPerformed(evt);
            }
        });

        jbQuanLyKH.setBackground(new java.awt.Color(0, 0, 0));
        jbQuanLyKH.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbQuanLyKH.setForeground(new java.awt.Color(255, 255, 255));
        jbQuanLyKH.setText("QUẢN LÝ KHÁCH HÀNG");
        jbQuanLyKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbQuanLyKHActionPerformed(evt);
            }
        });

        jbQuanLyTK.setBackground(new java.awt.Color(0, 0, 0));
        jbQuanLyTK.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbQuanLyTK.setForeground(new java.awt.Color(255, 255, 255));
        jbQuanLyTK.setText("QUẢN LÝ TÀI KHOẢN");
        jbQuanLyTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbQuanLyTKActionPerformed(evt);
            }
        });

        jbQuanLySach.setBackground(new java.awt.Color(0, 0, 0));
        jbQuanLySach.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbQuanLySach.setForeground(new java.awt.Color(255, 255, 255));
        jbQuanLySach.setText("QUẢN LÝ SÁCH");
        jbQuanLySach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbQuanLySachActionPerformed(evt);
            }
        });

        jbQuanLyPN.setBackground(new java.awt.Color(0, 0, 0));
        jbQuanLyPN.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbQuanLyPN.setForeground(new java.awt.Color(255, 255, 255));
        jbQuanLyPN.setText("QUẢN LÝ PHIẾU NHẬP");
        jbQuanLyPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbQuanLyPNActionPerformed(evt);
            }
        });

        jbQuanLyNCC.setBackground(new java.awt.Color(0, 0, 0));
        jbQuanLyNCC.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbQuanLyNCC.setForeground(new java.awt.Color(255, 255, 255));
        jbQuanLyNCC.setText("QUẢN LÝ NHÀ CUNG CẤP");
        jbQuanLyNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbQuanLyNCCActionPerformed(evt);
            }
        });

        jbTroLai.setBackground(new java.awt.Color(143, 68, 43));
        jbTroLai.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbTroLai.setForeground(new java.awt.Color(255, 255, 255));
        jbTroLai.setText("TRỞ LẠI");
        jbTroLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTroLaiActionPerformed(evt);
            }
        });

        jbQuanLyPN1.setBackground(new java.awt.Color(0, 0, 0));
        jbQuanLyPN1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbQuanLyPN1.setForeground(new java.awt.Color(255, 255, 255));
        jbQuanLyPN1.setText("THỐNG KÊ");
        jbQuanLyPN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbQuanLyPN1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbTroLai)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jbQuanLySach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbQuanLyNV, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jbQuanLyPN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(126, 126, 126)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbQuanLyNCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbQuanLyTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbQuanLyKH, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jbQuanLyPN1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbQuanLyNV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbQuanLyKH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbQuanLyTK, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbQuanLySach, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbQuanLyPN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbQuanLyNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jbQuanLyPN1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jbTroLai)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbQuanLyNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbQuanLyNVActionPerformed
        // TODO add your handling code here:
        QuanLyNV qlnv = new QuanLyNV(maTK, loaiTK);  // khởi tạo lớp đối tượng QuanLyNV
        qlnv.setVisible(true); // hiển thị giao diện Quản lý nhân viên
        this.dispose(); // đóng giao diện hiện tại
    }//GEN-LAST:event_jbQuanLyNVActionPerformed

    private void jbQuanLyKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbQuanLyKHActionPerformed
        // TODO add your handling code here:
        QuanLyKH qlkh = new QuanLyKH(maTK, loaiTK);
        qlkh.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbQuanLyKHActionPerformed

    private void jbQuanLySachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbQuanLySachActionPerformed
        // TODO add your handling code here
        QuanLySach qls = new QuanLySach(maTK, loaiTK);
        qls.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jbQuanLySachActionPerformed

    private void jbQuanLyTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbQuanLyTKActionPerformed
        // TODO add your handling code here:
        QuanLyTK qltk = new QuanLyTK(maTK, loaiTK);
        qltk.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jbQuanLyTKActionPerformed

    private void jbQuanLyPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbQuanLyPNActionPerformed
        // TODO add your handling code here:
        QuanLyPN qlpn = new QuanLyPN(maTK, loaiTK);
        qlpn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbQuanLyPNActionPerformed

    private void jbQuanLyNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbQuanLyNCCActionPerformed
        // TODO add your handling code here:
        QuanLyNCC qlncc = new QuanLyNCC(maTK, loaiTK);
        qlncc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbQuanLyNCCActionPerformed

    private void jbTroLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTroLaiActionPerformed
        // TODO add your handling code here:
        HomePage hp = new HomePage(maTK, loaiTK);
        hp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbTroLaiActionPerformed

    private void jbQuanLyPN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbQuanLyPN1ActionPerformed
        // TODO add your handling code here:
        BaoCaoThongKe bctk = new BaoCaoThongKe(maTK, loaiTK);
        bctk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbQuanLyPN1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String maTK, String loaiTK) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLy(maTK, loaiTK).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbQuanLyKH;
    private javax.swing.JButton jbQuanLyNCC;
    private javax.swing.JButton jbQuanLyNV;
    private javax.swing.JButton jbQuanLyPN;
    private javax.swing.JButton jbQuanLyPN1;
    private javax.swing.JButton jbQuanLySach;
    private javax.swing.JButton jbQuanLyTK;
    private javax.swing.JButton jbTroLai;
    // End of variables declaration//GEN-END:variables
}
